apiVersion: v1
kind: Service
metadata:
  name: ms-svc
  labels:
    app: dash
    component: ms-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    component: ms-rc
    enabled: "true"
