apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-<num>
  labels:
    assign-to: dashboard-storage
    name: mongo-pv-<num>
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    path: mongo-repo-vol0<num>
    endpoints: glusterfs-cluster
    readOnly: false
